export const SIGN_UP = "SIGN_UP"
export const LOGIN_USER = "LOGIN_USER"
export const GET_ALL_NOTES = "GET_ALL_NOTES"
export const ADD_NEW_NOTES = "ADD_NEW_NOTES"
export const DELETE_NOTE = "DELETE_NOTE"